---
- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ cbhealthagent_install_dir }}/{{ cbhealthagent_binary }}"
    dest: "/usr/bin/{{ cbhealthagent_binary }}"
    owner: root
    group: root
    state: link

- name: Stop cbhealthagent if installed
  block:
    # this will fail the verify first time of installation
    - name: Ensure cbhealthagent is stopped
      ansible.builtin.systemd:
        name: cbhealthagent
        enabled: true
        state: stopped
  rescue:
    # make sure that the service isn't actually installed
    - name: Get the list of services
      ansible.builtin.service_facts:

    - name: Verify that cbhealthagent is not installed
      ansible.builtin.assert:
        that:
          - _cbhealthagent_systemd_unit not in services

- name: Create cbhealthagent Service
  ansible.builtin.template:
    src: cbhealthagent.service.j2
    dest: "{{ _cbhealthagent_systemd_path }}/{{ _cbhealthagent_systemd_unit }}"
    owner: root
    group: root
    mode: 0755

- name: Create cbhealthagent Environment File
  ansible.builtin.template:
    src: EnvironmentFile.j2
    dest: "{{ cbhealthagent_conf_dir }}/{{ cbhealthagent_env_file }}"
    owner: "{{ cbhealthagent_user }}"
    group: "{{ cbhealthagent_user_group }}"
    mode: 0664

- name: Ensure cbhealthagent is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: cbhealthagent
    enabled: true
    state: started

- name: Wait for cbhealthagent to come up
  ansible.builtin.uri:
    url: "http://localhost:{{ cbhealthagent_http_port }}/agent/api/v1/ping"
    method: GET
  register: _result
  until: _result.status == 200
  retries: 60
  delay: 1
