---
- name: Install optional cbhealthagent dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - redhat-lsb-core
  when: cbhealthagent_install_dependencies

- name: cbhealthagent Group Creation
  block:
    - name: Check if the "{{ cbhealthagent_user_group }}" group exists
      ansible.builtin.getent:
        database: group
        key: "{{ cbhealthagent_user_group }}"
        fail_key: false

    - name: Set whether not the user group exists
      ansible.builtin.set_fact:
        __cbhealthagent_user_group_exists: "{{ ansible_facts.getent_group[cbhealthagent_user_group] is not none }}"

    - name: Add user group "{{ cbhealthagent_user_group }}"
      ansible.builtin.group:
        name: "{{ cbhealthagent_user_group }}"
        system: true
        state: present
      when: not __cbhealthagent_user_group_exists and cbhealthagent_user_group != 'root'

    - name: cbhealthagent Group Exists
      ansible.builtin.debug:
        msg: "The user group \"{{ cbhealthagent_user_group }}\" already exists and will not be modified, if modifying permissions please perform a separate task"
      when: __cbhealthagent_user_group_exists

- name: cbhealthagent User Creation
  block:
    - name: Check if the "{{ cbhealthagent_user }}" user exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ cbhealthagent_user }}"
        fail_key: false

    - name: Set whether not the user exists
      ansible.builtin.set_fact:
        __cbhealthagent_user_exists: "{{ ansible_facts.getent_passwd[cbhealthagent_user] is not none }}"

    - name: Add user "{{ cbhealthagent_user }}"
      ansible.builtin.user:
        name: "{{ cbhealthagent_user }}"
        comment: "cbhealthagent Account"
        groups:
          - "{{ cbhealthagent_user_group }}"
          - "{{ cbhealthagent_couchbase_user_group }}"
        system: true
        shell: "{{ cbhealthagent_user_shell }}"
        createhome: "{{ cbhealthagent_user_createhome }}"
      when: not __cbhealthagent_user_exists and cbhealthagent_user != 'root'

    - name: cbhealthagent User Exists
      ansible.builtin.debug:
        msg: "The user \"{{ cbhealthagent_user }}\" already exists and will not be modified, if modifying permissions please perform a separate task"
      when: __cbhealthagent_user_exists

- name: Install Directory
  block:
    - name: Create cbhealthagent Install Directory
      ansible.builtin.file:
        path: "{{ cbhealthagent_install_dir }}"
        state: directory
        owner: "{{ cbhealthagent_user }}"
        group: "{{ cbhealthagent_user_group }}"
        mode: 0775

    - name: Create cbhealthagent Conf Directory
      ansible.builtin.file:
        path: "{{ cbhealthagent_conf_dir }}"
        state: directory
        owner: "{{ cbhealthagent_user }}"
        group: "{{ cbhealthagent_user_group }}"
        mode: 0664

- name: Download cbhealthagent Binary to controller
  block:
    - name: Create cbhealthagent temp Directory
      become: false
      ansible.builtin.file:
        path: "{{ cbhealthagent_local_tmp_dir }}"
        state: directory
        mode: 0775
      delegate_to: localhost
      check_mode: false

    - name: Download cbhealthagent binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ _cbhealthagent_download_url }}"
        dest: "{{ cbhealthagent_local_tmp_dir }}/{{ cbhealthagent_binary }}"
        validate_certs: false
        mode: 0775
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Set local path
      ansible.builtin.set_fact:
        __cbhealthagent_local_binary_path: "{{ cbhealthagent_local_tmp_dir }}/{{ cbhealthagent_binary }}"

  when: (cbhealthagent_local_binary_path is not defined) or (cbhealthagent_local_binary_path | length == 0)

- name: Set local path
  ansible.builtin.set_fact:
    __cbhealthagent_local_binary_path: "{{ cbhealthagent_local_tmp_dir }}/{{ cbhealthagent_binary }}"
  when: cbhealthagent_local_binary_path is defined and cbhealthagent_local_binary_path | length > 0

- name: Propagate cbhealthagent binary
  ansible.builtin.copy:
    src: "{{ __cbhealthagent_local_binary_path }}"
    dest: "{{ cbhealthagent_install_dir }}/{{ cbhealthagent_binary }}"
    mode: 0775
    owner: "{{ cbhealthagent_user }}"
    group: "{{ cbhealthagent_user_group }}"
