---
- include_tasks:
    file: preflight.yml
    apply:
      become: true
      tags:
        - cbhealthagent_install
        - cbhealthagent_configure
        - cbhealthagent_run

- include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - cbhealthagent_install
  when: __cbhealthagent_do_install

- include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - cbhealthagent_configure
  tags:
    - cbhealthagent_configure
