---
- hosts: couchbase
  become: true
  vars:
    cbhealthagent_configure_firewalld: false
    couchbase_username: Administrator
    couchbase_password: password
    cbhealthagent_couchbase_install_path: /opt/couchbase
  pre_tasks:
    # pre_tasks happen before roles are executed / applied
    # if the cbhealthagent_configure_firewalld is true, make sure the service is installed before proceeding
    - name: Make sure firewalld is installed
      package:
        name: firewalld
        state: present
      when: cbhealthagent_configure_firewalld | default(false)
      tags:
        - cbhealthagent_firewalld
  roles:
    - couchbaselabs.cbhealthagent
  tasks:
    # tasks happen after roles are executed / applied
    # if the cbhealthagent_configure_firewalld is true, make sure the service is started
    - name: Make sure firewalld is started
      service:
        name: firewalld
        state: started
      when: cbhealthagent_configure_firewalld | default(false)
      tags:
        - cbhealthagent_firewalld
    - name: Add port {{ cbhealthagent_bind_port }} (cmos-exporter)
      ansible.posix.firewalld:
        port: "{{ cbhealthagent_bind_port }}/tcp"
        permanent: true
        state: enabled
      when: cbhealthagent_configure_firewalld | default(false)
      tags:
        - cbhealthagent_firewalld
    - name: Make sure firewalld is restarted
      service:
        name: firewalld
        state: restarted
      when: cbhealthagent_configure_firewalld | default(false)
      tags:
        - cbhealthagent_firewalld
